# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62lockchain.proto\"\x14\n\x12startMiningRequest\"%\n\x13startMiningResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"^\n\x10\x64iagnosisRequest\x12\x12\n\ndoctorname\x18\x01 \x01(\t\x12\x13\n\x0bpatientname\x18\x02 \x01(\t\x12\x14\n\x0cprescription\x18\x03 \x01(\t\x12\x0b\n\x03\x66\x65\x65\x18\x04 \x01(\x01\"#\n\x11\x64iagnosisResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"_\n\x11\x64iagnosis2Request\x12\x12\n\ndoctorname\x18\x01 \x01(\t\x12\x13\n\x0bpatientname\x18\x02 \x01(\t\x12\x14\n\x0cprescription\x18\x03 \x01(\t\x12\x0b\n\x03\x66\x65\x65\x18\x04 \x01(\x01\"$\n\x12\x64iagnosis2Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1b\n\x0bTransaction\x12\x0c\n\x04type\x18\x01 \x01(\t2\xb7\x01\n\nBlockchain\x12:\n\x0bstartMining\x12\x13.startMiningRequest\x1a\x14.startMiningResponse\"\x00\x12\x34\n\tdiagnosis\x12\x11.diagnosisRequest\x1a\x12.diagnosisResponse\"\x00\x12\x37\n\ndiagnosis2\x12\x12.diagnosis2Request\x1a\x13.diagnosis2Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blockchain_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTMININGREQUEST._serialized_start=20
  _STARTMININGREQUEST._serialized_end=40
  _STARTMININGRESPONSE._serialized_start=42
  _STARTMININGRESPONSE._serialized_end=79
  _DIAGNOSISREQUEST._serialized_start=81
  _DIAGNOSISREQUEST._serialized_end=175
  _DIAGNOSISRESPONSE._serialized_start=177
  _DIAGNOSISRESPONSE._serialized_end=212
  _DIAGNOSIS2REQUEST._serialized_start=214
  _DIAGNOSIS2REQUEST._serialized_end=309
  _DIAGNOSIS2RESPONSE._serialized_start=311
  _DIAGNOSIS2RESPONSE._serialized_end=347
  _TRANSACTION._serialized_start=349
  _TRANSACTION._serialized_end=376
  _BLOCKCHAIN._serialized_start=379
  _BLOCKCHAIN._serialized_end=562
# @@protoc_insertion_point(module_scope)
